### ISSUE TITLE
silence notice for missing w3m

### ISSUE THREAD

**Issue by steven-omaha** [hackerb9/vv#2]
Is there an option to silence the notice for missing `w3m` and `w3m-img`? From the source it doesn't seem like there is.

Would it be possible to either
- add a switch the silences the notice, so that I can alias `vv` to be `vv -q` or
- make it so that the notice is shown once, by executing `touch $XDG_CACHE_HOME/vv/notice` and checking if the file exists before the notice is printed.

**Comment by steven-omaha** [comment]
The same would apply for `pdfinfo` / `poppler-utils`.

**Comment by hackerb9** [comment]
I think this is a good idea. Additionally, if it is not easy for people to install optional dependencies, vv ought to only warn them when they try to use that feature, not every time it is run.

**Comment by hackerb9** [comment]
The latest version now warns about w3m and pdfinfo only when relevant functionality is used instead of at every startup. Please try it and let me know if that is sufficient or if it is lacking in some way. Thanks!

**Comment by steven-omaha** [comment]
Will do. Thanks!

**Comment by steven-omaha** [comment]
Works as you described. Thank you!
