### ISSUE TITLE
 Error: Your terminal does not report having sixel graphics support.

### ISSUE THREAD

**Issue by 621625** [hackerb9/vv#5]
Hi,

I'm Mr. C'Ocean, a very friendly guy.

I get these error messages:

Error: Your terminal does not report having sixel graphics support.

Please use a sixel capable terminal, such as xterm -ti vt340, or
ask your terminal manufacturer to add sixel support.

You may test your terminal by viewing a single image, like so:

convert  foo.jpg  -geometry 800x480  sixel:-

If your terminal actually does support sixel, please file a bug
report at http://github.com/hackerb9/vv/issues

(Please mention device attribute codes: ^[[?1;2c)

---

However I get those error messages in all the terminals that are supposed to support sixel. Xterm -ti vt340. Konsole. mlterm. So what's wrong? Raspberry Pi 4. Debian OS.

**Comment by hackerb9** [comment]
Thank you for the bug report. The attribute codes you mentioned are quite odd. That seems more like the output from a VT100 class terminal, not a VT340.  Did you try testing a single image using the `convert` command? 

At the command line, try typing:
```
xterm -ti vt340
```
and then run `vv` within that.

Please let me know the results of those tests.

Thanks.

**Comment by 621625** [comment]
Hi,

I have tried xterm -ti vt340 and then using vv. Result:

It doesn't work in the Userland debian emulator. Several error messages.

When trying it on a raspberry pi I get the error message above.

What works:

lsix works in the userland emulator. But it does not work on the raspberry pi. Same error message as before.

**Comment by 621625** [comment]
I have also tried updating xterm. It says already latest version.

**Comment by hackerb9** [comment]
What is your native language?

**Comment by 621625** [comment]
Slabagar.

Update:

It works now, seems like I may have forgotten to exit tmux first the other times. Cool.

Do you know some other sixel based packages that I can use to run gui's in the terminal, maybe watch a movie and so on?

**Comment by 621625** [comment]
And, importantly, do you know some multiplexer that supports sixel? Seems like neither tmux nor screen works. But I always use tmux, I need something like that.

**Comment by AutumnMeowMeow** [comment]
> And, importantly, do you know some multiplexer that supports sixel? Seems like neither tmux nor screen works. But I always use tmux, I need something like that.

[zellij](https://github.com/zellij-org/zellij) added sixel support last year: https://zellij.dev/news/sixel-search-statusbar/

It's also unsupported/archived/abandoned, but you could look at [jexer](https://gitlab.com/AutumnMeowMeow/jexer) / [xtermwm](https://gitlab.com/AutumnMeowMeow/xtermwm)

**Comment by hackerb9** [comment]
Thank you, Autumn!

**Comment by 621625** [comment]
In the libsixel github README.md there is a link to someone emulating a whole OS using sixel. Has anyone gotten that to work? That would be cool and I want to test it.

**Comment by AutumnMeowMeow** [comment]
@bitcoinmeetups Sixel by itself is just a wire protocol for transferring images, and with a good palette-based encoder it can feel like you've got 24-bit graphics.  See chafa and notcurses for even better and *much* faster sixel encoders than libsixel.  If you just want to display an X server, [enjoy this amusing video on the chafa blog](https://hpjansson.org/blag/2021/12/21/let-it-snow-21/) showing you how to do that using the X virtual frame buffer server and chafa's sixel encoder. :)

But for a whole OS-inside-xterm, you also need mouse support (SGR-Pixel mode now does that OK), probably better keyboard if you want modern shortcuts to work (several competing standards, seems to be coalescing around the kitty variety), and probably audio (no standard for that yet, unless you want really really ancient BBS-era single-toned "ANSI music").
